# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BarLine' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BarLine
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Google/Analytics'
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'
  pod 'Toast-Swift', '~> 1.3.0'
  pod 'NVActivityIndicatorView'
  pod 'KDCircularProgress'

  target 'BarLineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BarLineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
